language: rust
sudo: false

os:
  - linux
  - osx

rust:
  - 1.1.0
  - 1.2.0
  - 1.3.0
  - 1.4.0
  - stable
  - beta
  - nightly

before_script:
  - rustc -V
  - cargo -V

script:
  - cargo build
  - cargo test

after_success:
  # travis-cargo doesn't run on osx: https://github.com/huonw/travis-cargo/issues/26
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install 'travis-cargo<0.2' --user; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=$HOME/.local/bin:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis-cargo --only stable doc; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis-cargo --only stable doc-upload; fi
