language: rust
sudo: false

os:
  - linux
  - osx

rust:
  - 1.1.0
  - 1.2.0
  - 1.3.0
  - 1.4.0
  - stable
  - beta
  - nightly

before_script:
  - rustc -V
  - cargo -V
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo --only stable doc

after_success:
  - travis-cargo --only stable doc-upload
