(function() {var implementors = {};
implementors['assimp_sys'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Not.html' title='core::ops::Not'>Not</a> for <a class='struct' href='assimp_sys/config/struct.AiComponent.html' title='assimp_sys::config::AiComponent'>AiComponent</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Not.html' title='core::ops::Not'>Not</a> for <a class='struct' href='assimp_sys/config/struct.AiUVTransformFlags.html' title='assimp_sys::config::AiUVTransformFlags'>AiUVTransformFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Not.html' title='core::ops::Not'>Not</a> for <a class='struct' href='assimp_sys/struct.AiImporterFlags.html' title='assimp_sys::AiImporterFlags'>AiImporterFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Not.html' title='core::ops::Not'>Not</a> for <a class='struct' href='assimp_sys/struct.AiTextureFlags.html' title='assimp_sys::AiTextureFlags'>AiTextureFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Not.html' title='core::ops::Not'>Not</a> for <a class='struct' href='assimp_sys/struct.AiPrimitiveType.html' title='assimp_sys::AiPrimitiveType'>AiPrimitiveType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Not.html' title='core::ops::Not'>Not</a> for <a class='struct' href='assimp_sys/struct.AiPostProcessSteps.html' title='assimp_sys::AiPostProcessSteps'>AiPostProcessSteps</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Not.html' title='core::ops::Not'>Not</a> for <a class='struct' href='assimp_sys/struct.AiSceneFlags.html' title='assimp_sys::AiSceneFlags'>AiSceneFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Not.html' title='core::ops::Not'>Not</a> for <a class='struct' href='assimp_sys/struct.AiCompileFlags.html' title='assimp_sys::AiCompileFlags'>AiCompileFlags</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
